### PR TITLE
Py4j migration : remove legacy use

### PR DESCRIPTION
**Pull request by belkassaby**
Rebase branch on master and add update commit to remove legacy use.

As I cannot commit to the dascgitolite repo, I'm pushing this change here.

### CODE REVIEW

**Comment by mwebber** [comment]
> As I cannot commit to the dascgitolite repo, I'm pushing this change here
In which case, once your merge it, the change will be lost, because every 2 hours we overwrite the GitHub repo with the Gitolite one.

**Comment by belkassaby** [comment]
the py4j branch had not been rebased on master. it need to be. Once it is we can add the new commit on that branch : [8007d7d](https://github.com/DawnScience/scisoft-core/pull/9/commits/8007d7defa6239ba0e41a4b2d6f6c9aa9bb6c450)

**Comment by PeterC-DLS** [comment]
Hasn't the work you did in Feb last year already been merged? See commit [5e36c96](https://github.com/DawnScience/scisoft-core/commit/5e36c96884b359b4ccdd2773163948407cc83a08)

I don't see why you cannot create a new branch off tip?!?

**Comment by belkassaby** [comment]
true, i can create a new  branch as well. I just thought that I could also just rebase this one as it is a continuity of the task previously done.

**Comment by PeterC-DLS** [comment]
Once a branch has been merged, it is best not to reopen it. You can delete any branch on a repo and make a new one with the same name...

**Comment by belkassaby** [comment]
or I will do so.

**Comment by belkassaby** [comment]
Here is the new branch "py4j_legacy_removal" https://github.com/belkassaby/scisoft-core/tree/py4j_legacy_removal
Thanks for deleting for me the "py4j_migration" branch from the dascgitolite repo and also creating that branch on the scisoft-core repo as I still don't have any access to it.

**Pull request closed without merging**
